# Generated by Django 5.1.3 on 2025-02-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatterbox", "0002_banter"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
