# Generated by Django 4.2.19 on 2025-02-24 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chatterbox", "0003_profile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="banter",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="banter_like", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
